server:
  port: 8040
spring:
  application:
    name: @artifactId@

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://icecloud-center:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  routes:
    #    demoService:
    #      path: /demoService/**
    #      serviceId: spring-demo-service
    #简洁写法
    spring-demo-service: /demoService/**
  #排除某些路由
  ignored-patterns:
  - /spring-demo-service/port
